### ISSUE TITLE
Review jar org.grits.toolbox.ms.annotation.glycan.composition (SVN)

### ISSUE THREAD

**Issue by ReneRanzinger** [GritsToolbox/org.grits.toolbox#15]
There is a jar project in SVN - org.grits.toolbox.ms.annotation.glycan.composition. It does not have ant build instructions and I do not see if its used in any bundle or plugin. Is it still needed?

**Comment by senaarpinar** [comment]
This was created by Masaaki as part of handling glycan compositions in GRITS. It was work in progress and supposed to be used as a jar for other parts of the implementation. There is documentation in "doc" folder explaining the progress and the next steps. 
Since no one is actively working on extending GRITS, we don't need this plugin but we can confirm with Masaaki if he needs it.
