### ISSUE TITLE
Review bundles that were not migrated

### ISSUE THREAD

**Issue by ReneRanzinger** [GritsToolbox/org.grits.toolbox#4]
There are several bundles that seems not used and I did not migrated them. Are they needed?

* org.glygen
* edu.uga.cs.glycomics
* org.mihalis

**Comment by senaarpinar** [comment]
* org.mihalis is used in glycantree plugin. If we are not migrating that plugin, we don't need this one.
* org.glygen is created for Yukie to access the Glygenarray repository using the java client. I don't think she is using it and it is certainly not up-to-date. We can confirm with Yukie but I believe she is planning to make web service calls from her code instead of using the java client.
* edu.uga.cs.glycomics - I don't know anything about this plugin but quick search for references in the code didn't yield any results. It looks like it is not being used.
